Added alternate controller w/ bindings
Creekside-Robotics/2023-Offseason pull request #10
Opened 2023-07-01 18:37 UTC by ethanglocke

2023-07-01 21:36 UTC, josephhadad05 requested changes

2023-07-01 21:36 UTC, josephhadad05 commented on src/main/java/frc/robot/Constants.java
> +    public static int RetractIntake = 6;
When naming variables in java you typically use camelCase as opposed to PascalCase. You can read more about that here: https://www.freecodecamp.org/news/snake-case-vs-camel-case-vs-pascal-case-vs-kebab-case-whats-the-difference/

2023-07-01 21:36 UTC, josephhadad05 commented on src/main/java/frc/robot/RobotContainer.java
> +  private final DriverController alternaController = new DriverController(Constants.DeviceIds.driverController);
You used the controller id for the `mainController`, you need to create a new one for the `alernateController`.

Also, you misspelled alternate.

2023-07-25 01:31 UTC, josephhadad05 approved these changes
Looks good.

2023-07-25 01:31 UTC, josephhadad05 approved these changes

2023-07-25 10:04 UTC, paulelliott approved these changes
Looks great! Well done!

2023-07-28 20:53 UTC, merged